import {
  Building2,
  Calendar,
  Code2,
  Handshake,
  LayoutGrid,
  MessageSquare,
  Puzzle,
  Settings,
  UserPlus,
  Users,
  Zap,
  Bot,
  Radio,
  BookOpen,
  Clock,
  Globe,
  Palette,
  Workflow,
  ListOrdered,
  Target,
  Shield,
} from 'lucide-react';

const RELATED = {
  crm: {title: 'CRM Essentials', description: 'Leads, deals, contacts, and daily CRM work.', to: '/docs/crm-essentials', tone: 'violet'},
  pulse: {title: 'Pulse', description: 'Inbox, channels, and support conversations.', to: '/docs/pulse', tone: 'blue'},
  automation: {title: 'Automation', description: 'Workflows, sequences, and scoring.', to: '/docs/automation', tone: 'amber'},
  integrations: {title: 'Pulse Channel Integrations', description: 'WhatsApp, Messenger, and Instagram.', to: '/docs/integrations', tone: 'emerald'},
  administration: {title: 'Administration', description: 'Users, roles, and organization settings.', to: '/docs/administration', tone: 'slate'},
  developer: {title: 'Developer Resources', description: 'Lead capture and widget setup.', to: '/docs/developer', tone: 'indigo'},
};

export const CATEGORY_PAGES = {
  crmEssentials: {
    title: 'CRM Essentials',
    description:
      'Core documentation for managing customer relationships and daily CRM operations in CX Astra.',
    badgeLabel: 'Modules',
    documentationType: 'User Guide',
    audience: ['Sales Representatives'],
    guides: [
      {
        title: 'Leads',
        description: 'Capture, qualify, and convert sales prospects.',
        to: '/docs/Leads-Module/overview',
        Icon: UserPlus,
        tone: 'violet',
      },
      {
        title: 'Deals',
        description: 'Track opportunities through your sales pipeline.',
        to: '/docs/Deals-Module/overview',
        Icon: Handshake,
        tone: 'amber',
      },
      {
        title: 'Contacts',
        description: 'Manage people and customer relationships.',
        to: '/docs/Contacts-Module/overview',
        Icon: Users,
        tone: 'blue',
      },
      {
        title: 'Organizations',
        description: 'Organize company and account records.',
        to: '/docs/Organizations-Module/overview',
        Icon: Building2,
        tone: 'slate',
      },
      {
        title: 'Activities',
        description: 'Track tasks, meetings, notes, and follow-ups.',
        to: '/docs/Activities-Module/activities',
        Icon: LayoutGrid,
        tone: 'cyan',
      },
      {
        title: 'Calendar',
        description: 'Schedule and view CRM activities on the calendar.',
        to: '/docs/Calendar-Module/calendar',
        Icon: Calendar,
        tone: 'rose',
      },
    ],
    learningPath: [
      {title: 'Leads', to: '/docs/Leads-Module/overview'},
      {title: 'Contacts', to: '/docs/Contacts-Module/overview'},
      {title: 'Organizations', to: '/docs/Organizations-Module/overview'},
      {title: 'Deals', to: '/docs/Deals-Module/overview'},
      {title: 'Activities', to: '/docs/Activities-Module/activities'},
      {title: 'Calendar', to: '/docs/Calendar-Module/calendar'},
    ],
    relatedCategories: [RELATED.administration, RELATED.pulse, RELATED.automation],
  },

  pulse: {
    title: 'Pulse',
    description:
      'Configure Pulse Inbox, communication channels, Knowledge Base, support availability, and conversation management.',
    badgeLabel: 'Guides',
    documentationType: 'User Guide',
    audience: ['Support Teams', 'Administrators'],
    guides: [
      {
        title: 'Pulse Inbox',
        description: 'Work with omnichannel customer conversations.',
        to: '/docs/Pulse-Module/Pulse-Overview',
        Icon: MessageSquare,
        tone: 'blue',
      },
      {
        title: 'Channels',
        description: 'Connect and manage communication channels.',
        to: '/docs/Pulse-Settings/Channels',
        Icon: Radio,
        tone: 'cyan',
      },
      {
        title: 'Users & Access',
        description: 'Manage Pulse agents and access permissions.',
        to: '/docs/Pulse-Settings/Users&Access',
        Icon: Users,
        tone: 'violet',
      },
      {
        title: 'Assignment Rules',
        description: 'Route conversations to the right team members.',
        to: '/docs/Pulse-Settings/AssignmentRules',
        Icon: Target,
        tone: 'amber',
      },
      {
        title: 'Knowledge Base',
        description: 'Upload content used by Pulse AI responses.',
        to: '/docs/Pulse-Settings/KnowledgeBase',
        Icon: BookOpen,
        tone: 'emerald',
      },
      {
        title: 'Support Availability',
        description: 'Configure business hours and availability.',
        to: '/docs/Pulse-Settings/SupportAvailability',
        Icon: Clock,
        tone: 'rose',
      },
      {
        title: 'Global Settings',
        description: 'Manage workspace-wide Pulse preferences.',
        to: '/docs/Pulse-Settings/GlobalSettings',
        Icon: Settings,
        tone: 'slate',
      },
    ],
    learningPath: [
      {title: 'Pulse Inbox', to: '/docs/Pulse-Module/Pulse-Overview'},
      {title: 'Channels', to: '/docs/Pulse-Settings/Channels'},
      {title: 'Users & Access', to: '/docs/Pulse-Settings/Users&Access'},
      {title: 'Assignment Rules', to: '/docs/Pulse-Settings/AssignmentRules'},
      {title: 'Knowledge Base', to: '/docs/Pulse-Settings/KnowledgeBase'},
      {title: 'Support Availability', to: '/docs/Pulse-Settings/SupportAvailability'},
      {title: 'Global Settings', to: '/docs/Pulse-Settings/GlobalSettings'},
    ],
    relatedCategories: [RELATED.integrations, RELATED.administration, RELATED.crm],
  },

  administration: {
    title: 'Administration',
    description:
      'Manage organization settings, users, roles, teams, branding, localization, permissions, and CRM configuration.',
    badgeLabel: 'Guides',
    documentationType: 'Admin Guide',
    audience: ['Administrators'],
    guides: [
      {
        title: 'Organization Settings',
        description: 'Configure company profile and identity.',
        to: '/docs/Organization/Profile',
        Icon: Building2,
        tone: 'slate',
      },
      {
        title: 'User Management',
        description: 'Invite and manage workspace users.',
        to: '/docs/user-management/overview',
        Icon: Users,
        tone: 'blue',
      },
      {
        title: 'Roles',
        description: 'Define permissions and role-based access.',
        to: '/docs/user-management/roles',
        Icon: Shield,
        tone: 'violet',
      },
      {
        title: 'Teams',
        description: 'Configure teams, sharing, and access rules.',
        to: '/docs/user-management/Access',
        Icon: Users,
        tone: 'cyan',
      },
      {
        title: 'Branding',
        description: 'Customize logos and brand appearance.',
        to: '/docs/Organization/Branding',
        Icon: Palette,
        tone: 'rose',
      },
      {
        title: 'Localization',
        description: 'Set language, timezone, and regional preferences.',
        to: '/docs/Organization/Localization',
        Icon: Globe,
        tone: 'emerald',
      },
      {
        title: 'Work Schedule',
        description: 'Define working hours and holidays.',
        to: '/docs/Organization/WorkSchedule',
        Icon: Clock,
        tone: 'amber',
      },
    ],
    learningPath: [
      {title: 'Organization Settings', to: '/docs/Organization/Profile'},
      {title: 'User Management', to: '/docs/user-management/overview'},
      {title: 'Roles', to: '/docs/user-management/roles'},
      {title: 'Teams', to: '/docs/user-management/Access'},
      {title: 'Branding', to: '/docs/Organization/Branding'},
      {title: 'Localization', to: '/docs/Organization/Localization'},
      {title: 'Work Schedule', to: '/docs/Organization/WorkSchedule'},
    ],
    relatedCategories: [RELATED.crm, RELATED.automation, RELATED.developer],
  },

  automation: {
    title: 'Automation',
    description:
      'Configure workflows, sequences, assignment rules, and lead scoring to automate CRM processes.',
    badgeLabel: 'Guides',
    documentationType: 'User Guide',
    audience: ['Sales Managers', 'Administrators'],
    guides: [
      {
        title: 'Workflows',
        description: 'Build automated lead and deal processes.',
        to: '/docs/Automation/Workflows/Overview',
        Icon: Workflow,
        tone: 'amber',
      },
      {
        title: 'Sequences',
        description: 'Create multi-step outreach cadences.',
        to: '/docs/Automation/Sequences',
        Icon: ListOrdered,
        tone: 'violet',
      },
      {
        title: 'Assignment Rules',
        description: 'Automatically assign conversations and work.',
        to: '/docs/Pulse-Settings/AssignmentRules',
        Icon: Target,
        tone: 'blue',
      },
      {
        title: 'Lead Scoring',
        description: 'Score leads to prioritize follow-up.',
        to: '/docs/Automation/Scoring',
        Icon: Zap,
        tone: 'rose',
      },
    ],
    learningPath: [
      {title: 'Workflows', to: '/docs/Automation/Workflows/Overview'},
      {title: 'Sequences', to: '/docs/Automation/Sequences'},
      {title: 'Assignment Rules', to: '/docs/Pulse-Settings/AssignmentRules'},
      {title: 'Lead Scoring', to: '/docs/Automation/Scoring'},
    ],
    relatedCategories: [RELATED.crm, RELATED.pulse, RELATED.administration],
  },

  integrations: {
    title: 'Pulse Channel Integrations',
    description:
      'Connect CX Astra with external communication platforms and messaging channels.',
    badgeLabel: 'Guides',
    documentationType: 'Admin Guide',
    audience: ['Administrators'],
    guides: [
      {
        title: 'WhatsApp Business',
        description: 'Connect WhatsApp Business to Pulse.',
        to: '/docs/PulseChannelIntegrations/watsapp',
        Icon: MessageSquare,
        tone: 'emerald',
      },
      {
        title: 'Facebook Messenger & Instagram',
        description: 'Connect Messenger and Instagram messaging.',
        to: '/docs/PulseChannelIntegrations/FacebookMessenger&Instagram',
        Icon: Bot,
        tone: 'blue',
      },
    ],
    learningPath: [
      {title: 'WhatsApp Business', to: '/docs/PulseChannelIntegrations/watsapp'},
      {
        title: 'Facebook Messenger & Instagram',
        to: '/docs/PulseChannelIntegrations/FacebookMessenger&Instagram',
      },
    ],
    relatedCategories: [RELATED.pulse, RELATED.developer, RELATED.administration],
  },

  developer: {
    title: 'Developer Resources',
    description:
      'Technical documentation for implementing CX Astra within websites and applications.',
    badgeLabel: 'Guides',
    documentationType: 'Developer Guide',
    audience: ['Developers', 'Technical Implementers'],
    guides: [
      {
        title: 'Lead Capture',
        description: 'Capture and sync leads from external sources.',
        to: '/docs/Integrations/Lead-Capture',
        Icon: Code2,
        tone: 'indigo',
      },
      {
        title: 'Widget Setup',
        description: 'Install and configure the website widget.',
        to: '/docs/Pulse-Settings/Channels/Widget-Setup',
        Icon: Puzzle,
        tone: 'violet',
      },
    ],
    learningPath: [
      {title: 'Lead Capture', to: '/docs/Integrations/Lead-Capture'},
      {title: 'Widget Setup', to: '/docs/Pulse-Settings/Channels/Widget-Setup'},
    ],
    relatedCategories: [RELATED.integrations, RELATED.crm, RELATED.administration],
  },
};
